print(
    str(
        str(
            str(
                str(
                    str(
                        str(
                            str(
                                str(
                                    str(
                                        str(
                                            str(
                                                "Hello"
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)